name: RunAPI

env: 
  URL:  ${{secrets.SUPABASE_URL }}
  KEY:  ${{secrets.SUPABASE_KEY}}
  
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with: 
          python-version: '3.14'
          architecture: 'x64'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Depencies about Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
      - run: |
          mkdir pages
          echo "<h1>Hello GitHub Pages!</h1>" > pages/index.html
      - name: Build OpenAPI spec
        run: |
          python -c "from main import print_spec; print_spec()" > openapi_spec.json
      - name: Build ReDoc HTML
        run: |
            npm install -g redoc-cli
            redoc-cli bundle openapi_spec.json
            mv redoc-static.html pages/my_doc.html
      - uses: actions/upload-artifact@v6
        with:
          name: fastapi_doc
          path: pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: pages
      - run: poetry run main.py
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
